apiVersion: v1

kind: Pod

metadata:

  name: todo-pod
  namespace: django

spec:

  containers:

  - name: todo-app

    image: trainwithshubham/django-todo:latest

    ports:

    - containerPort: 8000

